// Generated by convex-ue-codegen. Do not edit by hand.
// Source: http://127.0.0.1:3210

#pragma once

// Typed native C++ wrappers for the deployed Convex functions.
// Compiles inside a UE module (depends on the ConvexClient module).

#include "CoreMinimal.h"
#include "ConvexValue.h"
#include "ConvexDelegates.h"
#include "ConvexPaginatedSubscription.h"

class UConvexClient;
class UConvexSubscription;

namespace ConvexApi
{

namespace Actions
{

	/// actions.js:echoAction (Action)
	/// args:    object{ x: any }
	/// returns: any
	void EchoAction(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnResult);

	/// actions.js:now (Action)
	/// args:    object{ }
	/// returns: any
	void Now(UConvexClient& Client, FConvexResultNative OnResult);

}  // namespace Actions

namespace Counters
{

	/// counters.js:get (Query)
	/// args:    object{ name: string }
	/// returns: any
	void Get(UConvexClient& Client, const FString& Name, FConvexResultNative OnResult);
	UConvexSubscription* WatchGet(UConvexClient& Client, const FString& Name, FConvexResultNative OnUpdate);

	/// counters.js:increment (Mutation)
	/// args:    object{ by?: number, name: string }
	/// returns: any
	void Increment(UConvexClient& Client, const FString& Name, const TOptional<double>& By, FConvexResultNative OnResult);

}  // namespace Counters

namespace Errors
{

	/// errors.js:throwConvexError (Query)
	/// args:    object{ }
	/// returns: any
	void ThrowConvexError(UConvexClient& Client, FConvexResultNative OnResult);
	UConvexSubscription* WatchThrowConvexError(UConvexClient& Client, FConvexResultNative OnUpdate);

	/// errors.js:throwPlainError (Query)
	/// args:    object{ }
	/// returns: any
	void ThrowPlainError(UConvexClient& Client, FConvexResultNative OnResult);
	UConvexSubscription* WatchThrowPlainError(UConvexClient& Client, FConvexResultNative OnUpdate);

}  // namespace Errors

namespace Files
{

	/// files.js:generateUploadUrl (Mutation)
	/// args:    object{ }
	/// returns: any
	void GenerateUploadUrl(UConvexClient& Client, FConvexResultNative OnResult);

	/// files.js:getMetadata (Query)
	/// args:    object{ storageId: id<_storage> }
	/// returns: any
	void GetMetadata(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnResult);
	UConvexSubscription* WatchGetMetadata(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnUpdate);

	/// files.js:getUrl (Query)
	/// args:    object{ storageId: id<_storage> }
	/// returns: any
	void GetUrl(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnResult);
	UConvexSubscription* WatchGetUrl(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnUpdate);

}  // namespace Files

namespace Messages
{

	/// messages.js:clearAll (Mutation)
	/// args:    object{ }
	/// returns: any
	void ClearAll(UConvexClient& Client, FConvexResultNative OnResult);

	/// messages.js:list (Query)
	/// args:    object{ channel: string }
	/// returns: any
	void List(UConvexClient& Client, const FString& Channel, FConvexResultNative OnResult);
	UConvexSubscription* WatchList(UConvexClient& Client, const FString& Channel, FConvexResultNative OnUpdate);

	/// messages.js:listPaginated (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: any
	void ListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult);
	UConvexSubscription* WatchListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);
	/// Subscribes messages:listPaginated as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription* WatchListPaginatedPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate);

	/// messages.js:listPaginatedDesc (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: any
	void ListPaginatedDesc(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult);
	UConvexSubscription* WatchListPaginatedDesc(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);
	/// Subscribes messages:listPaginatedDesc as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription* WatchListPaginatedDescPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate);

	/// messages.js:send (Mutation)
	/// args:    object{ author: string, body: string, channel: string }
	/// returns: any
	void Send(UConvexClient& Client, const FString& Author, const FString& Body, const FString& Channel, FConvexResultNative OnResult);

}  // namespace Messages

namespace Values
{

	/// values.js:echoMutation (Mutation)
	/// args:    object{ x: any }
	/// returns: any
	void EchoMutation(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnResult);

	/// values.js:echoQuery (Query)
	/// args:    object{ x: any }
	/// returns: any
	void EchoQuery(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnResult);
	UConvexSubscription* WatchEchoQuery(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnUpdate);

	/// values.js:kitchenSink (Query)
	/// args:    object{ }
	/// returns: any
	void KitchenSink(UConvexClient& Client, FConvexResultNative OnResult);
	UConvexSubscription* WatchKitchenSink(UConvexClient& Client, FConvexResultNative OnUpdate);

}  // namespace Values

}  // namespace ConvexApi
