// Generated by convex-ue-codegen. Do not edit by hand.
// Source: http://127.0.0.1:3210

#include "ConvexApiBP.h"

#include "ConvexClient.h"
#include "ConvexSubscription.h"

DEFINE_LOG_CATEGORY_STATIC(LogConvexApiBP, Log, All);

void UConvexApiActionsLibrary::EchoAction(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex EchoAction: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	Client->Action(TEXT("actions:echoAction"), Args, OnResult);
}

void UConvexApiActionsLibrary::Now(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex Now: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Action(TEXT("actions:now"), Args, OnResult);
}

void UConvexApiCountersLibrary::Get(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex Get: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	Client->Query(TEXT("counters:get"), Args, OnResult);
}

UConvexSubscription* UConvexApiCountersLibrary::WatchGet(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchGet: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	return Client->Subscribe(TEXT("counters:get"), Args, OnUpdate);
}

void UConvexApiCountersLibrary::Increment(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex Increment: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	Client->Mutation(TEXT("counters:increment"), Args, OnResult);
}

void UConvexApiErrorsLibrary::ThrowConvexError(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ThrowConvexError: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Query(TEXT("errors:throwConvexError"), Args, OnResult);
}

UConvexSubscription* UConvexApiErrorsLibrary::WatchThrowConvexError(UConvexClient* Client, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchThrowConvexError: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	return Client->Subscribe(TEXT("errors:throwConvexError"), Args, OnUpdate);
}

void UConvexApiErrorsLibrary::ThrowPlainError(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ThrowPlainError: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Query(TEXT("errors:throwPlainError"), Args, OnResult);
}

UConvexSubscription* UConvexApiErrorsLibrary::WatchThrowPlainError(UConvexClient* Client, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchThrowPlainError: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	return Client->Subscribe(TEXT("errors:throwPlainError"), Args, OnUpdate);
}

void UConvexApiFilesLibrary::GenerateUploadUrl(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex GenerateUploadUrl: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Mutation(TEXT("files:generateUploadUrl"), Args, OnResult);
}

void UConvexApiFilesLibrary::GetMetadata(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex GetMetadata: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	Client->Query(TEXT("files:getMetadata"), Args, OnResult);
}

UConvexSubscription* UConvexApiFilesLibrary::WatchGetMetadata(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchGetMetadata: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	return Client->Subscribe(TEXT("files:getMetadata"), Args, OnUpdate);
}

void UConvexApiFilesLibrary::GetUrl(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex GetUrl: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	Client->Query(TEXT("files:getUrl"), Args, OnResult);
}

UConvexSubscription* UConvexApiFilesLibrary::WatchGetUrl(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchGetUrl: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	return Client->Subscribe(TEXT("files:getUrl"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::ClearAll(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ClearAll: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Mutation(TEXT("messages:clearAll"), Args, OnResult);
}

void UConvexApiMessagesLibrary::List(UConvexClient* Client, const FString& Channel, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex List: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Client->Query(TEXT("messages:list"), Args, OnResult);
}

UConvexSubscription* UConvexApiMessagesLibrary::WatchList(UConvexClient* Client, const FString& Channel, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchList: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	return Client->Subscribe(TEXT("messages:list"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::ListPaginated(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ListPaginated: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client->Query(TEXT("messages:listPaginated"), Args, OnResult);
}

UConvexSubscription* UConvexApiMessagesLibrary::WatchListPaginated(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchListPaginated: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client->Subscribe(TEXT("messages:listPaginated"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::ListPaginatedDesc(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ListPaginatedDesc: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client->Query(TEXT("messages:listPaginatedDesc"), Args, OnResult);
}

UConvexSubscription* UConvexApiMessagesLibrary::WatchListPaginatedDesc(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchListPaginatedDesc: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client->Subscribe(TEXT("messages:listPaginatedDesc"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::Send(UConvexClient* Client, const FString& Author, const FString& Body, const FString& Channel, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex Send: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("author"), FConvexValue::String(Author));
	Args.Add(TEXT("body"), FConvexValue::String(Body));
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Client->Mutation(TEXT("messages:send"), Args, OnResult);
}

void UConvexApiValuesLibrary::EchoMutation(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex EchoMutation: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	Client->Mutation(TEXT("values:echoMutation"), Args, OnResult);
}

void UConvexApiValuesLibrary::EchoQuery(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex EchoQuery: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	Client->Query(TEXT("values:echoQuery"), Args, OnResult);
}

UConvexSubscription* UConvexApiValuesLibrary::WatchEchoQuery(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchEchoQuery: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	return Client->Subscribe(TEXT("values:echoQuery"), Args, OnUpdate);
}

void UConvexApiValuesLibrary::KitchenSink(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex KitchenSink: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Query(TEXT("values:kitchenSink"), Args, OnResult);
}

UConvexSubscription* UConvexApiValuesLibrary::WatchKitchenSink(UConvexClient* Client, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchKitchenSink: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	return Client->Subscribe(TEXT("values:kitchenSink"), Args, OnUpdate);
}

