// Generated by convex-ue-codegen. Do not edit by hand.
// Source: https://disciplined-cow-12.convex.cloud

#include "ConvexApi.h"

#include "ConvexClient.h"
#include "ConvexSubscription.h"

void ConvexApi::Actions::EchoAction(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	Client.ActionNative(TEXT("actions:echoAction"), Args, MoveTemp(OnResult));
}

void ConvexApi::Actions::Now(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.ActionNative(TEXT("actions:now"), Args, MoveTemp(OnResult));
}

void ConvexApi::Counters::Get(UConvexClient& Client, const FString& Name, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	Client.QueryNative(TEXT("counters:get"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Counters::WatchGet(UConvexClient& Client, const FString& Name, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	return Client.SubscribeNative(TEXT("counters:get"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Counters::Increment(UConvexClient& Client, const FString& Name, const TOptional<double>& By, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	if (By.IsSet())
	{
		Args.Add(TEXT("by"), FConvexValue::Float(By.GetValue()));
	}
	Client.MutationNative(TEXT("counters:increment"), Args, MoveTemp(OnResult));
}

void ConvexApi::Errors::ThrowConvexError(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.QueryNative(TEXT("errors:throwConvexError"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Errors::WatchThrowConvexError(UConvexClient& Client, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	return Client.SubscribeNative(TEXT("errors:throwConvexError"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Errors::ThrowPlainError(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.QueryNative(TEXT("errors:throwPlainError"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Errors::WatchThrowPlainError(UConvexClient& Client, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	return Client.SubscribeNative(TEXT("errors:throwPlainError"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Files::GenerateUploadUrl(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.MutationNative(TEXT("files:generateUploadUrl"), Args, MoveTemp(OnResult));
}

void ConvexApi::Files::GetMetadata(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	Client.QueryNative(TEXT("files:getMetadata"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Files::WatchGetMetadata(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	return Client.SubscribeNative(TEXT("files:getMetadata"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Files::GetUrl(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	Client.QueryNative(TEXT("files:getUrl"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Files::WatchGetUrl(UConvexClient& Client, const FString& /* Id<_storage> */ StorageId, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("storageId"), FConvexValue::String(StorageId));
	return Client.SubscribeNative(TEXT("files:getUrl"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Messages::ClearAll(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.MutationNative(TEXT("messages:clearAll"), Args, MoveTemp(OnResult));
}

void ConvexApi::Messages::List(UConvexClient& Client, const FString& Channel, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Client.QueryNative(TEXT("messages:list"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Messages::WatchList(UConvexClient& Client, const FString& Channel, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	return Client.SubscribeNative(TEXT("messages:list"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Messages::ListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client.QueryNative(TEXT("messages:listPaginated"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Messages::WatchListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client.SubscribeNative(TEXT("messages:listPaginated"), Args, MoveTemp(OnUpdate));
}

UConvexPaginatedSubscription* ConvexApi::Messages::WatchListPaginatedPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	return Client.SubscribePaginatedNative(TEXT("messages:listPaginated"), Args, InitialNumItems, MoveTemp(OnUpdate));
}

void ConvexApi::Messages::Send(UConvexClient& Client, const FString& Author, const FString& Body, const FString& Channel, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("author"), FConvexValue::String(Author));
	Args.Add(TEXT("body"), FConvexValue::String(Body));
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Client.MutationNative(TEXT("messages:send"), Args, MoveTemp(OnResult));
}

void ConvexApi::Values::EchoMutation(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	Client.MutationNative(TEXT("values:echoMutation"), Args, MoveTemp(OnResult));
}

void ConvexApi::Values::EchoQuery(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	Client.QueryNative(TEXT("values:echoQuery"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Values::WatchEchoQuery(UConvexClient& Client, const FConvexValue& X, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("x"), X);
	return Client.SubscribeNative(TEXT("values:echoQuery"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Values::KitchenSink(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.QueryNative(TEXT("values:kitchenSink"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Values::WatchKitchenSink(UConvexClient& Client, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	return Client.SubscribeNative(TEXT("values:kitchenSink"), Args, MoveTemp(OnUpdate));
}

