// Generated by convex-ue-codegen. Do not edit by hand.
// Source: https://disciplined-cow-12.convex.cloud

#pragma once

// Blueprint-callable wrappers for the deployed Convex functions.
// These files only compile inside a UE module (UHT-processed).

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ConvexValue.h"
#include "ConvexDelegates.h"

#include "ConvexApiBP.generated.h"

class UConvexClient;
class UConvexSubscription;

UCLASS()
class UConvexApiActionsLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|actions", meta = (DisplayName = "Convex actions:echoAction", ToolTip = "actions:echoAction (Action)\nargs: object{ x: any }"))
	static void EchoAction(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|actions", meta = (DisplayName = "Convex actions:now", ToolTip = "actions:now (Action)\nargs: object{ }"))
	static void Now(UConvexClient* Client, FConvexResultDelegate OnResult);

};

UCLASS()
class UConvexApiCountersLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|counters", meta = (DisplayName = "Convex counters:get", ToolTip = "counters:get (Query)\nargs: object{ name: string }"))
	static void Get(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|counters", meta = (DisplayName = "Convex Watch counters:get", ToolTip = "counters:get (Query) live subscription\nargs: object{ name: string }"))
	static UConvexSubscription* WatchGet(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|counters", meta = (DisplayName = "Convex counters:increment", ToolTip = "counters:increment (Mutation)\nargs: object{ by?: number, name: string }\noptional args omitted; use the C++ wrapper"))
	static void Increment(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnResult);

};

UCLASS()
class UConvexApiErrorsLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|errors", meta = (DisplayName = "Convex errors:throwConvexError", ToolTip = "errors:throwConvexError (Query)\nargs: object{ }"))
	static void ThrowConvexError(UConvexClient* Client, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|errors", meta = (DisplayName = "Convex Watch errors:throwConvexError", ToolTip = "errors:throwConvexError (Query) live subscription\nargs: object{ }"))
	static UConvexSubscription* WatchThrowConvexError(UConvexClient* Client, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|errors", meta = (DisplayName = "Convex errors:throwPlainError", ToolTip = "errors:throwPlainError (Query)\nargs: object{ }"))
	static void ThrowPlainError(UConvexClient* Client, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|errors", meta = (DisplayName = "Convex Watch errors:throwPlainError", ToolTip = "errors:throwPlainError (Query) live subscription\nargs: object{ }"))
	static UConvexSubscription* WatchThrowPlainError(UConvexClient* Client, FConvexResultDelegate OnUpdate);

};

UCLASS()
class UConvexApiFilesLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|files", meta = (DisplayName = "Convex files:generateUploadUrl", ToolTip = "files:generateUploadUrl (Mutation)\nargs: object{ }"))
	static void GenerateUploadUrl(UConvexClient* Client, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|files", meta = (DisplayName = "Convex files:getMetadata", ToolTip = "files:getMetadata (Query)\nargs: object{ storageId: id<_storage> }"))
	static void GetMetadata(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|files", meta = (DisplayName = "Convex Watch files:getMetadata", ToolTip = "files:getMetadata (Query) live subscription\nargs: object{ storageId: id<_storage> }"))
	static UConvexSubscription* WatchGetMetadata(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|files", meta = (DisplayName = "Convex files:getUrl", ToolTip = "files:getUrl (Query)\nargs: object{ storageId: id<_storage> }"))
	static void GetUrl(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|files", meta = (DisplayName = "Convex Watch files:getUrl", ToolTip = "files:getUrl (Query) live subscription\nargs: object{ storageId: id<_storage> }"))
	static UConvexSubscription* WatchGetUrl(UConvexClient* Client, const FString& StorageId, FConvexResultDelegate OnUpdate);

};

UCLASS()
class UConvexApiMessagesLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|messages", meta = (DisplayName = "Convex messages:clearAll", ToolTip = "messages:clearAll (Mutation)\nargs: object{ }"))
	static void ClearAll(UConvexClient* Client, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|messages", meta = (DisplayName = "Convex messages:list", ToolTip = "messages:list (Query)\nargs: object{ channel: string }"))
	static void List(UConvexClient* Client, const FString& Channel, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|messages", meta = (DisplayName = "Convex Watch messages:list", ToolTip = "messages:list (Query) live subscription\nargs: object{ channel: string }"))
	static UConvexSubscription* WatchList(UConvexClient* Client, const FString& Channel, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|messages", meta = (DisplayName = "Convex messages:listPaginated", ToolTip = "messages:listPaginated (Query)\nargs: object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }"))
	static void ListPaginated(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|messages", meta = (DisplayName = "Convex Watch messages:listPaginated", ToolTip = "messages:listPaginated (Query) live subscription\nargs: object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }"))
	static UConvexSubscription* WatchListPaginated(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|messages", meta = (DisplayName = "Convex messages:send", ToolTip = "messages:send (Mutation)\nargs: object{ author: string, body: string, channel: string }"))
	static void Send(UConvexClient* Client, const FString& Author, const FString& Body, const FString& Channel, FConvexResultDelegate OnResult);

};

UCLASS()
class UConvexApiValuesLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|values", meta = (DisplayName = "Convex values:echoMutation", ToolTip = "values:echoMutation (Mutation)\nargs: object{ x: any }"))
	static void EchoMutation(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|values", meta = (DisplayName = "Convex values:echoQuery", ToolTip = "values:echoQuery (Query)\nargs: object{ x: any }"))
	static void EchoQuery(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|values", meta = (DisplayName = "Convex Watch values:echoQuery", ToolTip = "values:echoQuery (Query) live subscription\nargs: object{ x: any }"))
	static UConvexSubscription* WatchEchoQuery(UConvexClient* Client, const FConvexValue& X, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|values", meta = (DisplayName = "Convex values:kitchenSink", ToolTip = "values:kitchenSink (Query)\nargs: object{ }"))
	static void KitchenSink(UConvexClient* Client, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|values", meta = (DisplayName = "Convex Watch values:kitchenSink", ToolTip = "values:kitchenSink (Query) live subscription\nargs: object{ }"))
	static UConvexSubscription* WatchKitchenSink(UConvexClient* Client, FConvexResultDelegate OnUpdate);

};

