// Generated by convex-ue-codegen. Do not edit by hand.
// Source: https://disciplined-cow-12.convex.cloud

// Typed AngelScript wrappers for the deployed Convex functions, for the
// Hazelight UnrealEngine-Angelscript fork. Put this file under the project's
// Script/ folder; it needs no build step and hot-reloads. Requires the Convex
// plugin. Functions with optional arguments have two overloads: required
// arguments only, and every argument. Named arguments work: Fn(Client,
// Name = "hits", By = 2.0, OnResult = Handler).

namespace ConvexApi::Actions
{
	/// actions.js:echoAction (Action)
	/// args:    object{ x: any }
	/// returns: any
	void EchoAction(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("x", X);
		Client.Action("actions:echoAction", Args, OnResult);
	}

	/// actions.js:now (Action)
	/// args:    object{ }
	/// returns: any
	void Now(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Action("actions:now", Args, OnResult);
	}
}

namespace ConvexApi::Counters
{
	/// counters.js:get (Query)
	/// args:    object{ name: string }
	/// returns: any
	void Get(UConvexClient Client, FString Name, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("name", Convex::MakeConvexString(Name));
		Client.Query("counters:get", Args, OnResult);
	}

	UConvexSubscription WatchGet(UConvexClient Client, FString Name, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("name", Convex::MakeConvexString(Name));
		return Client.Subscribe("counters:get", Args, OnUpdate);
	}

	/// counters.js:increment (Mutation)
	/// args:    object{ by?: number, name: string }
	/// returns: any
	void Increment(UConvexClient Client, FString Name, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("name", Convex::MakeConvexString(Name));
		Client.Mutation("counters:increment", Args, OnResult);
	}

	/// All arguments, including the optional ones.
	void Increment(UConvexClient Client, FString Name, float By, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("name", Convex::MakeConvexString(Name));
		Args.Add("by", Convex::MakeConvexFloat(By));
		Client.Mutation("counters:increment", Args, OnResult);
	}
}

namespace ConvexApi::Errors
{
	/// errors.js:throwConvexError (Query)
	/// args:    object{ }
	/// returns: any
	void ThrowConvexError(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Query("errors:throwConvexError", Args, OnResult);
	}

	UConvexSubscription WatchThrowConvexError(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		return Client.Subscribe("errors:throwConvexError", Args, OnUpdate);
	}

	/// errors.js:throwPlainError (Query)
	/// args:    object{ }
	/// returns: any
	void ThrowPlainError(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Query("errors:throwPlainError", Args, OnResult);
	}

	UConvexSubscription WatchThrowPlainError(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		return Client.Subscribe("errors:throwPlainError", Args, OnUpdate);
	}
}

namespace ConvexApi::Files
{
	/// files.js:generateUploadUrl (Mutation)
	/// args:    object{ }
	/// returns: any
	void GenerateUploadUrl(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Mutation("files:generateUploadUrl", Args, OnResult);
	}

	/// files.js:getMetadata (Query)
	/// args:    object{ storageId: id<_storage> }
	/// returns: any
	void GetMetadata(UConvexClient Client, FString StorageId, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("storageId", Convex::MakeConvexString(StorageId));
		Client.Query("files:getMetadata", Args, OnResult);
	}

	UConvexSubscription WatchGetMetadata(UConvexClient Client, FString StorageId, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("storageId", Convex::MakeConvexString(StorageId));
		return Client.Subscribe("files:getMetadata", Args, OnUpdate);
	}

	/// files.js:getUrl (Query)
	/// args:    object{ storageId: id<_storage> }
	/// returns: any
	void GetUrl(UConvexClient Client, FString StorageId, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("storageId", Convex::MakeConvexString(StorageId));
		Client.Query("files:getUrl", Args, OnResult);
	}

	UConvexSubscription WatchGetUrl(UConvexClient Client, FString StorageId, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("storageId", Convex::MakeConvexString(StorageId));
		return Client.Subscribe("files:getUrl", Args, OnUpdate);
	}
}

namespace ConvexApi::Messages
{
	/// messages.js:clearAll (Mutation)
	/// args:    object{ }
	/// returns: any
	void ClearAll(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Mutation("messages:clearAll", Args, OnResult);
	}

	/// messages.js:list (Query)
	/// args:    object{ channel: string }
	/// returns: any
	void List(UConvexClient Client, FString Channel, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Client.Query("messages:list", Args, OnResult);
	}

	UConvexSubscription WatchList(UConvexClient Client, FString Channel, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		return Client.Subscribe("messages:list", Args, OnUpdate);
	}

	/// messages.js:listPaginated (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: any
	void ListPaginated(UConvexClient Client, FString Channel, FConvexValue PaginationOpts, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Args.Add("paginationOpts", PaginationOpts);
		Client.Query("messages:listPaginated", Args, OnResult);
	}

	UConvexSubscription WatchListPaginated(UConvexClient Client, FString Channel, FConvexValue PaginationOpts, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Args.Add("paginationOpts", PaginationOpts);
		return Client.Subscribe("messages:listPaginated", Args, OnUpdate);
	}

	/// Subscribes messages:listPaginated as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription WatchListPaginatedPaginated(UConvexClient Client, FString Channel, int InitialNumItems, FConvexPaginatedSnapshotDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		return Client.SubscribePaginated("messages:listPaginated", Args, InitialNumItems, OnUpdate);
	}

	/// messages.js:send (Mutation)
	/// args:    object{ author: string, body: string, channel: string }
	/// returns: any
	void Send(UConvexClient Client, FString Author, FString Body, FString Channel, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("author", Convex::MakeConvexString(Author));
		Args.Add("body", Convex::MakeConvexString(Body));
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Client.Mutation("messages:send", Args, OnResult);
	}
}

namespace ConvexApi::Values
{
	/// values.js:echoMutation (Mutation)
	/// args:    object{ x: any }
	/// returns: any
	void EchoMutation(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("x", X);
		Client.Mutation("values:echoMutation", Args, OnResult);
	}

	/// values.js:echoQuery (Query)
	/// args:    object{ x: any }
	/// returns: any
	void EchoQuery(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("x", X);
		Client.Query("values:echoQuery", Args, OnResult);
	}

	UConvexSubscription WatchEchoQuery(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("x", X);
		return Client.Subscribe("values:echoQuery", Args, OnUpdate);
	}

	/// values.js:kitchenSink (Query)
	/// args:    object{ }
	/// returns: any
	void KitchenSink(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Query("values:kitchenSink", Args, OnResult);
	}

	UConvexSubscription WatchKitchenSink(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		return Client.Subscribe("values:kitchenSink", Args, OnUpdate);
	}
}

