// Generated by convex-ue-codegen. Do not edit by hand.
// Source: http://127.0.0.1:3210

// Typed AngelScript wrappers for the deployed Convex functions, for the
// Hazelight UnrealEngine-Angelscript fork. Put this file under the project's
// Script/ folder; it needs no build step and hot-reloads. Requires the Convex
// plugin. Object shapes the functions declare are script structs, decoded and
// encoded by the ConvexApi::Types namespace; a function with a declared
// return takes a typed delegate. Functions with optional arguments have two
// overloads: required arguments only, and every argument. Named arguments
// work: Fn(Client, Name = "hits", By = 2.0, OnResult = Handler).

/// object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number }
struct FConvexApiMessagesListPaginatedPaginationOpts
{
	FConvexValue Cursor;
	FConvexValue EndCursor;
	bool bHasEndCursor = false; // EndCursor was present
	float Id = 0.0;
	bool bHasId = false; // Id was present
	float MaximumBytesRead = 0.0;
	bool bHasMaximumBytesRead = false; // MaximumBytesRead was present
	float MaximumRowsRead = 0.0;
	bool bHasMaximumRowsRead = false; // MaximumRowsRead was present
	float NumItems = 0.0;
};

namespace ConvexApi::Types
{
	FConvexApiMessagesListPaginatedPaginationOpts DecodeMessagesListPaginatedPaginationOpts(FConvexValue Value)
	{
		FConvexApiMessagesListPaginatedPaginationOpts Out;
		Out.Cursor = Value.Get("cursor");
		if (Value.HasField("endCursor"))
		{
			Out.bHasEndCursor = true;
			Out.EndCursor = Value.Get("endCursor");
		}
		if (Value.HasField("id"))
		{
			Out.bHasId = true;
			Out.Id = Value.Get("id").AsFloat();
		}
		if (Value.HasField("maximumBytesRead"))
		{
			Out.bHasMaximumBytesRead = true;
			Out.MaximumBytesRead = Value.Get("maximumBytesRead").AsFloat();
		}
		if (Value.HasField("maximumRowsRead"))
		{
			Out.bHasMaximumRowsRead = true;
			Out.MaximumRowsRead = Value.Get("maximumRowsRead").AsFloat();
		}
		Out.NumItems = Value.Get("numItems").AsFloat();
		return Out;
	}

	FConvexValue Encode(FConvexApiMessagesListPaginatedPaginationOpts In)
	{
		TMap<FString, FConvexValue> Fields;
		Fields.Add("cursor", In.Cursor);
		if (In.bHasEndCursor)
		{
			Fields.Add("endCursor", In.EndCursor);
		}
		if (In.bHasId)
		{
			Fields.Add("id", Convex::MakeConvexFloat(In.Id));
		}
		if (In.bHasMaximumBytesRead)
		{
			Fields.Add("maximumBytesRead", Convex::MakeConvexFloat(In.MaximumBytesRead));
		}
		if (In.bHasMaximumRowsRead)
		{
			Fields.Add("maximumRowsRead", Convex::MakeConvexFloat(In.MaximumRowsRead));
		}
		Fields.Add("numItems", Convex::MakeConvexFloat(In.NumItems));
		return Convex::MakeConvexObject(Fields);
	}
}

namespace ConvexApi::Actions
{
	/// actions.js:echoAction (Action)
	/// args:    object{ x: any }
	/// returns: any
	void EchoAction(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("x", X);
		Client.Action("actions:echoAction", _Args, OnResult);
	}

	/// actions.js:now (Action)
	/// args:    object{ }
	/// returns: any
	void Now(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		Client.Action("actions:now", _Args, OnResult);
	}
}

namespace ConvexApi::Counters
{
	/// counters.js:get (Query)
	/// args:    object{ name: string }
	/// returns: any
	void Get(UConvexClient Client, FString Name, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("name", Convex::MakeConvexString(Name));
		Client.Query("counters:get", _Args, OnResult);
	}

	UConvexSubscription WatchGet(UConvexClient Client, FString Name, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("name", Convex::MakeConvexString(Name));
		return Client.Subscribe("counters:get", _Args, OnUpdate);
	}

	/// counters.js:increment (Mutation)
	/// args:    object{ by?: number, name: string }
	/// returns: any
	void Increment(UConvexClient Client, FString Name, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("name", Convex::MakeConvexString(Name));
		Client.Mutation("counters:increment", _Args, OnResult);
	}

	/// All arguments, including the optional ones.
	void Increment(UConvexClient Client, FString Name, float By, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("name", Convex::MakeConvexString(Name));
		_Args.Add("by", Convex::MakeConvexFloat(By));
		Client.Mutation("counters:increment", _Args, OnResult);
	}
}

namespace ConvexApi::Errors
{
	/// errors.js:throwConvexError (Query)
	/// args:    object{ }
	/// returns: any
	void ThrowConvexError(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		Client.Query("errors:throwConvexError", _Args, OnResult);
	}

	UConvexSubscription WatchThrowConvexError(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		return Client.Subscribe("errors:throwConvexError", _Args, OnUpdate);
	}

	/// errors.js:throwPlainError (Query)
	/// args:    object{ }
	/// returns: any
	void ThrowPlainError(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		Client.Query("errors:throwPlainError", _Args, OnResult);
	}

	UConvexSubscription WatchThrowPlainError(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		return Client.Subscribe("errors:throwPlainError", _Args, OnUpdate);
	}
}

namespace ConvexApi::Files
{
	/// files.js:generateUploadUrl (Mutation)
	/// args:    object{ }
	/// returns: any
	void GenerateUploadUrl(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		Client.Mutation("files:generateUploadUrl", _Args, OnResult);
	}

	/// files.js:getMetadata (Query)
	/// args:    object{ storageId: id<_storage> }
	/// returns: any
	void GetMetadata(UConvexClient Client, FString StorageId, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("storageId", Convex::MakeConvexString(StorageId));
		Client.Query("files:getMetadata", _Args, OnResult);
	}

	UConvexSubscription WatchGetMetadata(UConvexClient Client, FString StorageId, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("storageId", Convex::MakeConvexString(StorageId));
		return Client.Subscribe("files:getMetadata", _Args, OnUpdate);
	}

	/// files.js:getUrl (Query)
	/// args:    object{ storageId: id<_storage> }
	/// returns: any
	void GetUrl(UConvexClient Client, FString StorageId, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("storageId", Convex::MakeConvexString(StorageId));
		Client.Query("files:getUrl", _Args, OnResult);
	}

	UConvexSubscription WatchGetUrl(UConvexClient Client, FString StorageId, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("storageId", Convex::MakeConvexString(StorageId));
		return Client.Subscribe("files:getUrl", _Args, OnUpdate);
	}
}

namespace ConvexApi::Messages
{
	/// messages.js:clearAll (Mutation)
	/// args:    object{ }
	/// returns: any
	void ClearAll(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		Client.Mutation("messages:clearAll", _Args, OnResult);
	}

	/// messages.js:list (Query)
	/// args:    object{ channel: string }
	/// returns: any
	void List(UConvexClient Client, FString Channel, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		Client.Query("messages:list", _Args, OnResult);
	}

	UConvexSubscription WatchList(UConvexClient Client, FString Channel, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		return Client.Subscribe("messages:list", _Args, OnUpdate);
	}

	/// messages.js:listPaginated (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: any
	void ListPaginated(UConvexClient Client, FString Channel, FConvexApiMessagesListPaginatedPaginationOpts PaginationOpts, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		_Args.Add("paginationOpts", ConvexApi::Types::Encode(PaginationOpts));
		Client.Query("messages:listPaginated", _Args, OnResult);
	}

	UConvexSubscription WatchListPaginated(UConvexClient Client, FString Channel, FConvexApiMessagesListPaginatedPaginationOpts PaginationOpts, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		_Args.Add("paginationOpts", ConvexApi::Types::Encode(PaginationOpts));
		return Client.Subscribe("messages:listPaginated", _Args, OnUpdate);
	}

	/// Subscribes messages:listPaginated as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription WatchListPaginatedPaginated(UConvexClient Client, FString Channel, int InitialNumItems, FConvexPaginatedSnapshotDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		return Client.SubscribePaginated("messages:listPaginated", _Args, InitialNumItems, OnUpdate);
	}

	/// messages.js:listPaginatedDesc (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: any
	void ListPaginatedDesc(UConvexClient Client, FString Channel, FConvexApiMessagesListPaginatedPaginationOpts PaginationOpts, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		_Args.Add("paginationOpts", ConvexApi::Types::Encode(PaginationOpts));
		Client.Query("messages:listPaginatedDesc", _Args, OnResult);
	}

	UConvexSubscription WatchListPaginatedDesc(UConvexClient Client, FString Channel, FConvexApiMessagesListPaginatedPaginationOpts PaginationOpts, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		_Args.Add("paginationOpts", ConvexApi::Types::Encode(PaginationOpts));
		return Client.Subscribe("messages:listPaginatedDesc", _Args, OnUpdate);
	}

	/// Subscribes messages:listPaginatedDesc as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription WatchListPaginatedDescPaginated(UConvexClient Client, FString Channel, int InitialNumItems, FConvexPaginatedSnapshotDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		return Client.SubscribePaginated("messages:listPaginatedDesc", _Args, InitialNumItems, OnUpdate);
	}

	/// messages.js:send (Mutation)
	/// args:    object{ author: string, body: string, channel: string }
	/// returns: any
	void Send(UConvexClient Client, FString Author, FString Body, FString Channel, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("author", Convex::MakeConvexString(Author));
		_Args.Add("body", Convex::MakeConvexString(Body));
		_Args.Add("channel", Convex::MakeConvexString(Channel));
		Client.Mutation("messages:send", _Args, OnResult);
	}
}

namespace ConvexApi::Values
{
	/// values.js:echoMutation (Mutation)
	/// args:    object{ x: any }
	/// returns: any
	void EchoMutation(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("x", X);
		Client.Mutation("values:echoMutation", _Args, OnResult);
	}

	/// values.js:echoQuery (Query)
	/// args:    object{ x: any }
	/// returns: any
	void EchoQuery(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("x", X);
		Client.Query("values:echoQuery", _Args, OnResult);
	}

	UConvexSubscription WatchEchoQuery(UConvexClient Client, FConvexValue X, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		_Args.Add("x", X);
		return Client.Subscribe("values:echoQuery", _Args, OnUpdate);
	}

	/// values.js:kitchenSink (Query)
	/// args:    object{ }
	/// returns: any
	void KitchenSink(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> _Args;
		Client.Query("values:kitchenSink", _Args, OnResult);
	}

	UConvexSubscription WatchKitchenSink(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> _Args;
		return Client.Subscribe("values:kitchenSink", _Args, OnUpdate);
	}
}

